name: apiverve_incometax
description: Income Tax Brackets is a tool for retrieving US federal income tax bracket data by year. It returns tax rates, income ranges, and standard deductions for all filing statuses.
version: 1.1.14
homepage: https://apiverve.com/marketplace/incometax?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/incometax-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
